### ISSUE TITLE
Add support for torch.hub

### ISSUE THREAD

**Issue by Randl** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#1]
Allow to download weights automatically by using [PyTorch Hub](https://pytorch.org/docs/stable/hub.html)

**Comment by VCasecnikovs** [comment]
Done! You can now use torch hub
`torch.hub.load("VCasecnikovs/Yet-Another-YOLOv4-Pytorch", "yolov4", pretrained=True)`
