### ISSUE TITLE
Training samples with no bboxes

### ISSUE THREAD

**Issue by cooked-sashimi** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#11]
Hello I was wondering how do you deal with training samples that don't have bboxes?

**Comment by VCasecnikovs** [comment]
Hello, thank you for the question. Now it is fixed. There was a problem with PyTorch's max function, it doesn't work with 0 shaped tensors, but all is fixed now. It is fixed at commit d010272d0483ca20d7f5c06bc2146d01f9e36164.
