### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by yerzhan7orazayev** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#12]
What are the step to run the model on sample image?
What are the required package list?

Could you please clearly state these instructions?

**Comment by VCasecnikovs** [comment]
Hello, the only library You need is PyTorch.
To use PytTorch Lightning, you will need PyTorch Lightning too.
To test on video, please, use video_demo.py.
You can also look at this notebook, here all is explained.
Training YOLOv4 .ipynb

**Comment by yerzhan7orazayev** [comment]
@VCasecnikovs 
Thanks for prompt response. 

I am wondering, if one modifies the dict coco_dict in `video_demo.py` (line 8) to be only `coco_dict = {0: 'person'}` does it that model will predict only **person** class? Thanks.
