### ISSUE TITLE
How to get these values?

### ISSUE THREAD

**Issue by yerzhan7orazayev** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#15]
Dear @VCasecnikovs,

How to get the confidence value next to object labels in the following picture: https://github.com/VCasecnikovs/Yet-Another-YOLOv4-Pytorch/blob/master/github_imgs/from_net.png? 
I want to get these values when running this code for example:
`bboxes, labels = utils.get_bboxes_from_anchors(anchors, 0.4, 0.5, coco_dict)
`

**Comment by VCasecnikovs** [comment]
You can use utils.get_image_with_bboxes.
The 4th index of bbox is confidence
