### ISSUE TITLE
For Y(target),what does "Num of img to which this anchor belongs" mean?

### ISSUE THREAD

**Issue by AlexLuya** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#2]
Would you please give a concrete example?

**Comment by VCasecnikovs** [comment]
Hello, thanks for the question. So basically dataset returns y as a tensor of (A, 6), where A is the number of anchors in the data bunch. The first column for which you are referring to basically is an index to distinct to which image in data bunch this anchor belongs to. For example, if it is 0, then it belongs to the first image (x[0]). If it is 1, it belongs to the second (x[1]). Maybe I should change num to index.

**Comment by AlexLuya** [comment]
Thanks,I think when you say 'anchor',you mean 'box',am I right?In yolo,'anchor' has special meaning,if I were  right,more editing is needed ^_^

**Comment by VCasecnikovs** [comment]
Yes, you are right. Will fix it. Thanks for issue
