### ISSUE TITLE
PL version

### ISSUE THREAD

**Issue by xixi-nobody** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#20]
Hello, after reading your code carefully, I feel I have benefited a lot. There are some problems in the ipynb of operation training, which may be related to the different operation environment. Can you tell me the specific operation environment?

**Comment by VCasecnikovs** [comment]
Hello, the main problem could be pytorch lightning. The correct version is 0.7.6. Other libraries didn't break backwards compatibility, so it is ok to use the last version.

**Comment by xixi-nobody** [comment]
> Hello, the main problem could be pytorch lightning. The correct version is 0.7.6. Other libraries didn't break backwards compatibility, so it is ok to use the last version.

Thank you. With your help, I succeeded in solving the problem.
