### ISSUE TITLE
Convert weights between darknet repo( AlexeyAB's repo ) and this repo

### ISSUE THREAD

**Issue by robosina** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#4]
I have a model in darknet repository which I want to convert that weights and retrain using this repo, can we do that?

**Comment by VCasecnikovs** [comment]
Hello, thank you for the question. If you want to get Alexey's weights, I have posted them in the description of the repository. If you want to convert your own weights, I haven't implemented this feature yet, but I can share a code of how to convert tianxioamo's weights, also I saw a lot of repos, which convert weights from darknet to pytorch.

**Comment by robosina** [comment]
@VCasecnikovs , Thank you very much I will try what you said.

**Comment by robosina** [comment]
Could you please share your code to convert tianxioamo's weights?

**Comment by VCasecnikovs** [comment]
Hello, sorry for so late sending. Here it is.
[weights_tianxiaomo2my.zip](https://github.com/VCasecnikovs/Yet-Another-YOLOv4-Pytorch/files/5336854/weights_tianxiaomo2my.zip)

**Comment by robosina** [comment]
@VCasecnikovs Thank you so much
