### ISSUE TITLE
AP ?

### ISSUE THREAD

**Issue by LukeAI** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#5]
Thanks for this repo. !

I was wondering if you had any numbers you could share comparing what AP this repo. is able to train to on coco or similar and maybe FPS. - just so we can compare to AlexeyAB's darknet.

**Comment by VCasecnikovs** [comment]
Hello, I have AP calculation. I'll try to add it to repo on weekends.

**Comment by LukeAI** [comment]
thanks, I guess my question is more:

Have you trained on coco with this repo? If so, what AP did you achieve?

**Comment by VCasecnikovs** [comment]
I'm sorry that I haven't implemented AP yet. Also, I haven't tested on COCO dataset. But I tested on my local datasets. Had 0.6+
