### ISSUE TITLE
best_ious, best_n = ious.max(0) RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity

### ISSUE THREAD

**Issue by azharshaikh06** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#7]

**Comment by VCasecnikovs** [comment]
Good evening. Thank you for the issue. As I understand error happens to be in this lines of code.
```
# Get anchors with best iou
ious = torch.stack([self.bbox_wh_iou(anchor, gwh) for anchor in anchors])
best_ious, best_n = ious.max(0)
```
I assume, that You have set amount of anchors to zero and this is the main problem why you get this error. 
If I haven't solved your problem, please describe how to get this error, so I could debug it.

**Comment by azharshaikh06** [comment]
Hi first off thank you for the very well written code! I was able to solve the error when I set batchsize>1.

**Comment by VCasecnikovs** [comment]
Hello, your solution may not solve the error. It mainly happened because of the bug, when the number of targets is zero. This was solved with the latest commit.
