### ISSUE TITLE
nan value predicted sometimes for pred_conf

### ISSUE THREAD

**Issue by azharshaikh06** [VCasecnikovs/Yet-Another-YOLOv4-Pytorch#9]
loss_conf_noobj = F.binary_cross_entropy(pred_conf[noobj_mask], tconf[noobj_mask])
RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered

pred_conf
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],

         [[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]],

**Comment by VCasecnikovs** [comment]
Hello,
thank You for Your question.
Pred_conf comes from the network. So somewhere in the network something explodes and gives you such a result. Could You tell me Your network configuration, otherwise I would not be able to help You?
Best regards,
Vadims.

**Comment by azharshaikh06** [comment]
the only change I have made is to the backbone, the number of blocks i am using is 1,2,2,1 instead of 2,8,8,4
hparams = {
    "pretrained" : False,
    "train_ds" : data_path+"train.txt",
    "valid_ds" : data_path+"val.txt",
    "img_size" : 800,
    "bs" : 2,
    "momentum": 0.9,
    "wd": 0.001,
    "lr": 0.01, #0.0001 for 3layer tinyyolo 
    "epochs" : 2,
    "pct_start" : 10/100,
    "iou_threshold": 0.5,
    "confidence_threshold": 0.5,
    
    "optimizer" : "Ranger",
    "flat_epochs" : 15,
    "cosine_epochs" : 10,
    "scheduler" : "Cosine Delayed", 
    
    "SAT" : True,
    "epsilon" : 0.1,
    "SAM" : False,
    "ECA" : False,
    "WS" : False,
    "Dropblock" : True,
    "iou_aware" : False,
    "coord" : False,
    "hard_mish" : False,
    "asff" : False,
    "repulsion_loss" : False,
    "acff" : False,
    "bcn" : False,
    "mbn" : False,
}

**Comment by azharshaikh06** [comment]
Could you tell me how to convert this model to tiny-yolov4

**Comment by VCasecnikovs** [comment]
Hello, I would recommend you to cancel each if them separately and find if there are some problems. Maybe you could do some Traceback where it fails. Also, if You have change a backbone problem could be somewhere there... Take a look, maybe you have some problems there.
About tiny yolo. I haven't implemented it. To implement it you should take only half of the channels in route nodes (concatenation).
https://github.com/Tianxiaomo/pytorch-YOLOv4/issues/125

**Comment by VCasecnikovs** [comment]
Maybe the error was because you had 0 target images. If yes, the last update should fix it. Sorry for bug. d010272d0483ca20d7f5c06bc2146d01f9e36164 #11
